M48
; DRILL file {KiCad (6.0.7-1)-1} date Thursday, February 09, 2023 at 10:12:35 PM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-02-09T22:12:35-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7-1)-1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0866
%
G90
G05
T1
X5.7Y-3.6
X5.7Y-4.8
X6.9Y-3.6
X6.9Y-4.8
T0
M30
